### ISSUE TITLE
Many samples fail to process

### ISSUE THREAD

**Issue by Yoric** [binast/binjs-fbssdc#3]
In #2, I landed a size benchmark.

Attempting to use it on https://github.com/Yoric/real-js-samples, my logs show 5000+ files that cannot be processed due to some error while executing the Python codebase. I don't know if it's a bug in `binjs_encode`, in `fbssdc`, in Python, or a discrepancy between files. Regardless, that's a lot. We need to investigate.

@dominiccooney, could you take a look?

**Comment by dominiccooney** [comment]
In short, no, I'm not interested in this.

I checked out real-js-samples and started running a simple round-trip script like test.sh on them. It's still running but after the first ~3,000 files; 3,294 of them have round-tripped OK. The other 65 failed in ways unrelated to the format: parse errors from node, mostly because the "JavaScript" files are HTML; binjs_encode panicking with FromJSONError because of the shape produced by Shift. There's one interesting panic dumping 20190220/https%3A/player.ivideosmart.com/ivxplayer/v1/js/all.02201641.js:

````
thread 'large stack dedicated thread' panicked at 'This name is both non-const-lexical-bound and var-bound: IdentifierName(Dynamic("f"))', crates/binjs_es6/src/scopes.rs:243:13
````

None of the failed when encoding or decoding; none of them produced different JSON output.

I would like to find bugs with the format encoder/decoder. It's possible your larger dictionary is tickling a bug. If there are crashes encoding or decoding files or errors round-tripping then, sure, I'm interested. Please send me a list of the relevant files and some stack traces. If you have a log it might make sense to share that, it would save my time.

**Comment by Yoric** [comment]
I haven't had the opportunity to get `test.sh` to work on my machine yet, but that's on the roadmap.  For the moment, all I have is the result of `bench/sample_directory.py`.

So, I went ahead and debugged it. So far, I found two issues:

- recursion limit is too small (perhaps it's set differently on your machine and mine?);
- the scaffolding (I wrote) doesn't handle properly empty files.

See #3. I'll launch another run to see if any errors remain.

**Comment by dominiccooney** [comment]
Ah yeah, you're right—I had increased the recursion limit.

If you're spawning bpy.py you could just use the encoder directly and avoid the cost of that spawn.

**Comment by Yoric** [comment]
Yes, I refactored `sample_directory.py` to avoid spawning `bpy.py`. That's why it *only* took 6h :)

**Comment by Yoric** [comment]
(also, interesting time travel in these comments)

**Comment by dominiccooney** [comment]
In the end I could round trip all the files I could get into ASTs (although I used a small dictionary) which indicates there's no problem in the decoder in these ~6k files.

There were 104 failures:

77 Shift parse errors:
- 26 about async arrow functions
- 15 about parsing markup as JS; these are mostly 404 messages
- 14 about async functions
- 9 about object literal spreads
- 4 about async methods in classes, eg 20190220/https%3A/www.redditstatic.com/desktop2x/CommentsPage.c7e0e686cb7cdbf40999.js at character 10402
- rest are miscellaneous

21 FromJSONErrors, ie binjs_encode's schema expectations were violated; note I'm using binjs_encode circa February, probably 1cb28e5eef807c2a759b28bba2ec195363575370.
- Most of them are expected Parameter, got BindingWithDefault.
- Some are an array which is optional in Shift but binjs_encode requires, for example real-js-samples/20190416/NotificationsPrePromptLoader.4c1df3f5a231c230d931.js

3 Stack overflows parsing JSON (`JsonError(ExceededDepthLimit)`)

3 Binding consistency problems:
- 20190220/https%3A/player.ivideosmart.com/ivxplayer/v1/js/all.02201641.js
- 20190416/all.04181208.js
- 20190416/CollectionCommentsPage%7ECommentsPage%7EExplore%7EFrontpage%7EGovernanceReleaseNotesModal%7EModListing%7EModQueu%7E1084d5fc.fc0dd8e4bc
35d0c1945c.js

**Comment by Yoric** [comment]
The fixes above seem to handle all the failures that were in the Python code. I'll investigate the rest once I have time.
